<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Smash Academie - Lexique</title>
    <?php include "assets/php/head.php" ?>
  </head>
  <body>
    <header>
      <div class="background">
        <?php include "assets/php/header.php" ?>
      </div>
    </header>
    <main>
      <h1 data-aos="fade-down" class="title">LE LEXIQUE</h1>
        <hr>
        <div data-aos="fade-down" class="presentation">
          <p>Ici, vous retrouverez un lexique plus que complet sur Super Smash Bros.</p>
          <p>Le CTRL+F peut être très utile et recommandé sur cette page.</p>
          <h2 class="redac" style="text-align: justify;">Notions de base</h2>
          <p style="text-align: justify;"><strong>Jab </strong><em>(Attaque simple)</em><strong> :</strong> Attaque basique d'un personnage lorsqu'il n'exécute aucune autre action.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Appuyer sur A sur place.</p>
          <hr />
          <p style="text-align: justify;"><strong>Jab Cancel</strong><strong>&nbsp;</strong><strong>:</strong> La quasi totalité des Jabs étant des multihits, certains peuvent être arrêtés au moment de votre choix ce qui vous permet le plus souvent d'exécuter une autre action par la suite.&nbsp;</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Incliner le stick directionnel vers le bas avec un certain timing pendant un hit du jab de votre choix.</p>
          <hr />
          <p style="text-align: justify;"><strong>Hit&nbsp;</strong><strong>:</strong> Un hit désigne de manière générale un coup net ne possédant qu'une seule phase de hitbox.</p>
          <hr />
          <p style="text-align: justify;"><strong>Multihit&nbsp;</strong><strong>:</strong> Désigne un coup possédant plusieurs hits et possédant ainsi plusieurs phases de hitbox.</p>
          <hr />
          <p style="text-align: justify;"><strong>Running&nbsp;</strong><strong>:</strong> Action de courir.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Donner un coup sec avec le stick directionnel et maintenir appuyé.</p>
          <hr />
          <p style="text-align: justify;"><strong>Walking&nbsp;</strong><strong>:</strong> Action de marcher.&nbsp;À&nbsp;noter que vous pouvez modifer la vitesse du walking selon l'inclinaison de votre stick directionnel.&nbsp;</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Appuyer légèrement sur le stick directionnel et maintenir.</p>
          <hr />
          <p style="text-align: justify;"><strong>Jumping&nbsp;</strong><strong>:</strong>&nbsp;Action de sauter. Selon les personnages, vous pouvez exécuter un nombre limité de sauts lorsque vous êtes en l'air, la longueur et la hauteur de votre saut dépendant de votre personnage. Le plus souvent un personnage ne possède qu'un deuxième saut (appelé double-saut) lorsque vous êtes en l'air. Il existe toutefois des exceptions avec certains personnages appelées Sauts Multiples, comme Metaknight, Roudoudou et Kirby qui possèdent 6 sauts (1 au sol et 5 en l'air), King Dedede qui possède 5 sauts (1 au sol et 4 en l'air), Pit qui possède 4 sauts (1 au sol et 3 en l'air) et Dracaufeu qui possède 3 sauts (1 au sol et 2 en l'air). Votre "quota" de sauts est remis à 0 une fois que vous avez retouché le sol ou que vous vous accrochez au bord du terrain.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Appuyer sur X ou Y (ou le Tap Jump si celui-ci est activé) lorsque vous êtes au sol. Pour le double-saut ou saut multiple : Appuyer sur X ou Y (ou le Tap Jump) lorsque vous êtes en l'air.</p>
          <hr />
          <p style="text-align: justify;"><strong>Short Hop&nbsp;</strong><em>(Miny Jump ou Tiny Jump)</em><strong>&nbsp;:</strong>&nbsp;Permet de réduire la hauteur et longueur de votre saut à partir du sol.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Exécuter une faible pression sur le bouton X ou Y (ou le Tap Jump) lorsque vous êtes au sol.</p>
          <hr />
          <p style="text-align: justify;"><strong>Glide&nbsp;</strong><strong>:</strong>&nbsp;Le glide consiste à planer après un saut avec un personnage. Seuls les personnages possédant des ailes (Metaknight, Dracaufeu et Pit) peuvent effectuer le glide.&nbsp;À&nbsp;noter que si vous exécutez votre Glide sur votre dernier saut, une fois le glide terminé vous serez en <em>Helpless mode</em>. Votre glide prend fin lorsque votre personnage n'a plus aucune vitesse de planage, lorsque vous effectuez une Glide Attack, lorsque vous touchez le sol ou lorsque vous appuyez sur B pendant le glide.&nbsp;À&nbsp;noter aussi que vous ne pouvez exécuter qu'un seul glide par phase aérienne, vous devez soit retoucher le sol, soit vous accrocher au bord pour pouvoir refaire votre Glide. Autre point, si vous vous écrasez au sol pendant un glide vous serez en position <em>Tech Chasing</em> pour votre adversaire.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Après un saut, appuyer et maintenir la touche de saut ou faire droite-gauche avec le stick directionnel (la 1ère direction étant celle du dos de votre personnage) pour entamer un Glide.</p>
          <hr />
          <p style="text-align: justify;"><strong>Glide Attack&nbsp;</strong><strong>:</strong>&nbsp;Désigne le nom de la seule attaque que vous pouvez exécuter pendant une phase de Glide.&nbsp;À&nbsp;noter que si vous effectuez une glide attack juste avant de toucher le sol vous annulez tout le cooldown de celle-ci (Voir <em>Autocancelling Aerials</em>).&nbsp;</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Appuyer sur A pendant une phase de Glide.</p>
          <hr />
          <p style="text-align: justify;"><strong>Smash&nbsp;</strong><em>(Attaque smashée)</em><strong>&nbsp;:</strong>&nbsp;Attaque servant tradionnellement à mettre K.O. un adversaire.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Stick C ou Direction + A (en même temps et en donnant un coup sec sur le stick directionnel, peut être chargée en restant appuyée sur A). À noter que seul le Usmash peut être utilisé en courant.</p>
          <p style="margin-left: 40px; text-align: justify;">•&nbsp;Smash avant : Forward Smash = Fsmash&nbsp;<br />
          • Smash haut : Up Smash = Usmash<br />
          • Smash bas : Down Smash = Dsmash</p>
          <p style="text-align: justify;">Si vous êtes touché pendant que vous chargez un smash votre knockback augmentera de 20%.</p>
          <hr />
          <p style="text-align: justify;"><strong>Special&nbsp;</strong><em>(Attaque spéciale)</em><strong>&nbsp;:</strong>&nbsp;Chaque personnage du jeu peut utiliser 4 attaques (ou plus si l'on compte les moves customs) qui lui sont spécifiques.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Direction puis B.&nbsp;</p>
          <p style="margin-left: 40px; text-align: justify;">•&nbsp;Attaque spéciale neutre : B neutre = Neutral B<br />
          • Attaque spéciale côté : B côté = Side B<br />
          • Attaque spéciale haut : B haut = Up B<br />
          • Attaque spéciale bas : B bas = Down B</p>
          <hr />
          <p style="text-align: justify;"><strong>Tilt&nbsp;</strong><em>(Attaque normale orientée)</em><strong>&nbsp;:</strong>&nbsp;Attaque non smashée d'un personnage.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Direction puis A. À noter qu'un Tilt ne peut être utilisé en courant (dash)</p>
          <p style="margin-left: 40px; text-align: justify;">•&nbsp;Tilt avant : Forward Tilt = Flt&nbsp;<br />
          • Tilt haut : Up Tilt = Ult&nbsp;<br />
          • Tilt bas : Down Tilt = Dlt</p>
          <hr />
          <p style="text-align: justify;"><strong>Aerial&nbsp;</strong><em>(Attaque aérienne)</em><strong>&nbsp;:</strong>&nbsp;Attaque pouvant uniquement être utilisée dans les airs pour taper son adversaire.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Appuyer sur A et une direction (selon l'aerial voulu) lorsque vous êtes en l'air.</p>
          <p style="margin-left: 40px; text-align: justify;">•&nbsp;Aerial avant : Forward Air / Aerial Forward A = Fair / AFA<br />
          • Aerial neutre : Neutral Air / Aerial Neutral A = Nair / ANA<br />
          • Aerial haut : Up Air / Aerial Up A = Uair / AUA<br />
          • Aerial bas : Down Air / Aerial Down A = Dair / ADA<br />
          • Aerial arrière : Back Air / Aerial Back A = Bair / ABA</p>
          <hr />
          <p style="text-align: justify;"><strong>Dash Attack&nbsp;</strong><em>(Attaque en courant)</em><strong> :</strong> Attaque permettant de toucher son adversaire tout en courant.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Courir puis A / Stick C vers le bas ou le côté.</p>
          <hr />
          <p style="text-align: justify;"><strong>Tap Jump&nbsp;</strong><strong>:</strong>&nbsp;Le Tap Jump désigne le saut qu'il est possible de faire avec le stick directionnel. A noter que vous pouvez désactiver le Tap Jump (qui est mis par défaut) dans les modifcations de commandes de votre manette.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Donner un coup sec vers le haut avec le stick directionnel.</p>
          <hr />
          <p style="text-align: justify;"><strong>Shield&nbsp;</strong><em>(Bouclier)</em><strong>&nbsp;:</strong>&nbsp;Action permettant d'utiliser son bouclier et ainsi de prévenir la majeure partie des attaques du jeu.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Appuyer sur R ou L.</p>
          <p style="text-align: justify;">À noter que le bouclier a une durée limitée, si vous en abusez trop il se réduit et vous défend de moins en moins, et si le bouclier est complètement affaibli il se brise. On nomme ceci le <em>Shield Breaking</em>.</p>
          <p style="text-align: justify;">A noter aussi que l'on peut diriger son bouclier vers l'avant, le haut ou le bas, on nomme cela le <em>Shield-directing</em>.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Appuyer sur R ou L puis incliner doucement le stick directionnel vers l'avant, le haut ou le bas. A noter encore que même si votre bouclier est actif, vous pouvez être touché par une attaque. On nomme cela le <em>Shield Stabbing</em>.</p>
          <hr />
          <p style="text-align: justify;"><strong>Shield Breaking&nbsp;</strong><strong>:</strong>&nbsp;Lorsque votre bouclier est complètement affaibli il se brise, on appelle ça le Shield Breaking. Pendant une phase de Shield Breaking vous vous retrouvez sans défense, dans l'incapacité de bouger pendant plusieurs secondes, et toute attaque vous propulsera 20% plus loin. Pour sortir d'un état de Shield Breaking, vous devez soit attendre que votre personnage reprenne connaissance tout seul, soit qu'il se fasse toucher (sauf par une attaque qui n'inflige pas de Hitstun).</p>
          <p style="text-align: justify;">À&nbsp;noter que Rondoudou est le seul personnage dont le shield breaking cause la mort directe vers le haut, sauf si le stage est extrêmement grand verticalement ou si un obstacle se trouve entre lui et le haut du stage.</p>
          <hr />
          <p style="text-align: justify;"><strong>Shield-stab&nbsp;</strong><strong>:</strong>&nbsp;Lorsque votre bouclier est affaibli vous prenez le risque que votre Hurtbox dépasse de celui-ci, le shield-stab définit donc le moment où une attaque touche votre hurtbox même si votre bouclier est activé, la protection de celui-ci étant ignorée. Pour éviter cela il est conseillé d'utiliser le Shield-directing.</p>
          <hr />
          <p style="text-align: justify;"><strong>Edge&nbsp;</strong><strong>:</strong>&nbsp;De manière générale, ce terme définit les bords du terrain où l'on peut s'accrocher. A noter que dans Brawl lorsque vous exécutez un recovery move en direction de l'edge vous exécutez un auto-sweetspot sur celui-ci, c'est -à-dire que vous vous accrochez automatiquement à celui-ci sans laisser se terminer le recovery move. Lorsque vous vous accrochez à l'edge vous bénéficiez d'un certain nombre de frames d'invincibilité. Pour vous accrocher au bord il faut que votre hurtbox rentre en contact avec la zone d'accroche (dite zone de sweetspot) de l'edge.</p>
          <hr />
          <p style="text-align: justify;"><strong>Ledge Options&nbsp;</strong><strong>:</strong>&nbsp;Lorsque vous êtes accroché au bord, vous êtes minimisé dans vos possibilités. Chacune de ces possibilités a des avantages et inconvénients et la mauvaise utilisation de celles-ci vous expose à des punitions sévères voir fatales la plupart du temps (Edgeguard). Voici vos possibilités une fois accroché au bord :</p>
          <p style="text-align: justify;">•&nbsp;<em>Attaquer</em>&nbsp;(Appuyer sur A lorsque vous êtes accroché au bord) : Aussi appelé ledge attack. La portée et la priorité de votre ledge attack dépend entièrement de votre personnage.&nbsp;À&nbsp;noter que chaque personnage possède 2 ledge attacks, une lorsqu'il est à moins de 100% et une lorsqu'il est à 100% ou plus. Le plus souvent la ledge attack à partir de 100% est beaucoup plus lente, a moins de portée, et moins de priorité que votre ledge attack à moins de 100%. Il n'y a pas vraiment d'avantage ou de défaut général à cette possibilité puisqu'elle est extrêmement variable selon les personnages. Il convient juste de se rappeler que parmi toutes les possibilités celle-ci est l'une des plus longues à finir mais qu'en cas de réussite elle vous permet d'éloigner votre adversaire du bord en lui faisant des dégâts. Cela vous permet de revenir avec plus de facilité sur le terrain car moins sujet à une punition. Cependant si votre adversaire connaît parfaitement vos distances de ledgeattack et qu'il a prévu que vous allez utiliser celle-ci, vous vous exposez à une très grosse punition due aux longues frames de cooldown.</p>
          <p style="text-align: justify;">•&nbsp;<em>Se lever normalement</em><em>&nbsp;</em>(Appuyer avec le stick directionnel dans la direction où se trouve le bord lorsque vous êtes accroché à celui-ci) : Se lever normalement est l'une des meilleures manières de sortir de ledge si elle n'est pas prédite. En faisant cela vous disposerez de frames d'invincibilité et vous serez très proche du bord, ce qui limite les punitions. Le plus souvent, un adversaire qui voudra tenter de vous punir se mettra à une certaine distance de sorte à ce qu'il ne soit pas touché par une ledgeattack. C'est donc une très bonne solution pour prendre l'adversaire à contre-pied s'il s'attendait à vous voir faire une roulade ou une attaque. Cependant, faites attention aux cas où votre adversaire avait prévu une sortie de ledge en saut (edgehop), et dans de très moindres cas, en ledgeattack.</p>
          <p style="text-align: justify;">• <i>Rouler&nbsp;</i>(Appuyer sur R ou L lorsque vous êtes accroché au bord) : Il existe 2 sortes roulades, une s'exécutant automatiquement lorsque vous êtes à moins de 100%, et une autre s'exécutant automatiquement lorsque vous êtes à plus de 100%. La vitesse et la longueur de la roulade dépendent entièrement de votre personnage mais dans tous les cas une sorte de ledge en roulade à moins de 100% sera toujours plus rapide que celle à plus de 100%. Lorsque vous exécutez celle-ci vous bénéficiez de frames d'invincibilité plus longues que lorsque vous vous relevez normalement, cependant votre cooldown est énorme. En utilisant cette ledge option vous vous exposez à de très grosses punitions si votre adversaire a prévu le coup ou s'il avait anticipé une ledgeattack/relevée normale. Cependant cette sorte de ledge est la méthode le plus safe si votre adversaire s'attend à un edgehop par exemple.</p>
          <p style="text-align: justify;">•&nbsp;<i>Sauter</i><i>&nbsp;</i>(Appuyer sur X, Y ou le tap jump lorsque vous êtes accroché au bord) : Sortir de ledge en sautant fait aussi partie des moyens les plus safe pour s'extraire selon votre personnage. En effet chaque personnage a une amplitude de saut (en ledge) différente. Les frames de cooldown sont quasi-inexistantes et vous pouvez faire un aerial, une airdodge, etc... Cependant si votre adversaire a prévu le coup vous vous exposez à une assez grosse punition selon la puissance des aerial attacks de l'adversaire. Vous pouvez aussi vous faire punir si l'adversaire avait anticipé un edge-hop ou, dans une moindre mesure, en se relevant normalement. Cependant sortir de ledge en sautant reste l'un des moyens les plus safe si l'adversaire s'attend à une ledgeattack ou une roulade.</p>
          <p style="text-align: justify;">•&nbsp;<i>Edge-hop&nbsp;</i>: Voir Edge-hopping : Le plus souvent, c'est l'une des meilleurs options si votre personnage a un bon 2ème saut ou a des sauts multiples et/ou a un bon Forward Air (ou de bonnes attaques aériennes en général). Vous ne bénéficiez de quasiment aucune frame de cooldown. Son seul inconvénient est la punition assurée si l'adversaire s'y attend ou que vous vous foirez. Le but du edge-hop est justement de punir l'adversaire s'il prévoit autre chose que ce move, mais ne vous laissez pas surprendre et ne vous ratez pas sinon c'est presque le retour de bâton assuré.</p>
          <p style="text-align: justify;">•&nbsp;<i>Stalling sur ledge</i><i>&nbsp;</i>(se lâcher du bord en appuyant sur bas ou la direction opposée au bord avec votre stick directionnel et effectuer votre second saut puis une tether attack ou un recovery move pour vous ré-accrocher directement au bord) : Cette solution ne vous permet pas de sortir de ledge mais seulement de jouer avec les nerfs de votre adversaire et ainsi de rendre votre choix (avec les 5 solutions proposées au-dessus) de plus en plus imprévisible. Selon votre personnage le stalling sur ledge peut être très difficile à punir, mais prenez garde car si il y a théoriquement mort subite à la fin du match et que vous avez dépassé les 40 ledgegrabs, vous serez déclaré perdant du match. Soyez donc vigilant.</p>
          <hr />
          <p style="text-align: justify;"><strong>Dodge&nbsp;</strong><strong>:</strong>&nbsp;Action d'exécuter une esquive afin d'éviter une attaque qui aurait dû vous toucher directement. Il existe différentes formes d'esquive :</p>
          <p style="text-align: justify;">•&nbsp;<em>Spot Dodge</em>&nbsp;: Esquive sur place. Appuyer sur R ou L puis donner un coup sec au stick directionnel vers le bas.</p>
          <p style="text-align: justify;">•&nbsp;<em>Air Dodge</em><em>&nbsp;</em>: Esquive dans les airs. Appuyer sur R ou L lorsque vous êtes en l'air.</p>
          <p style="text-align: justify;">•&nbsp;<i>Rolls :&nbsp;</i>Esquive en roulant. Appuyer sur R ou L puis donner un coup sec au stick directionnel vers la gauche ou la droite.</p>
          <hr />
          <p style="text-align: justify;"><strong>Grabs &amp; Throws</strong><strong>&nbsp;</strong><em>(</em><em>Attraper et jeter son adversaire</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Plus communément appelée "Chope", cette action permet d'attraper votre adversaire et de l'éjecter. Les choppes sont l'un des seuls vrais remèdes pour attaquer un adversaire en train d'utiliser son bouclier. différentes formes de chopes sont à distinguer :</p>
          <p style="text-align: justify;">•&nbsp;<em>Grab</em>&nbsp;: Attraper l'adversaire sur place. Appuyer sur Z.</p>
          <p style="text-align: justify;">•&nbsp;<em>Dashing Grab / Running Grab</em><em>&nbsp;</em>: Attraper l'adversaire en dashing / running. Dashing / Running puis Z.</p>
          <p style="text-align: justify;">•&nbsp;<i>Shield Grab </i><i>:&nbsp;</i>Attraper l'adversaire pendant l'utilisation de votre bouclier. R ou L + A.</p>
          <p style="text-align: justify;">•&nbsp;<em>Reverse Grab</em><em>&nbsp;</em>: Attraper son adversaire en se retournant sur place. Stick directionnel dans la direction opposée + Z.</p>
          <p style="text-align: justify;">•&nbsp;<i>Pivot Grab</i><i>&nbsp;:&nbsp;</i>Attraper son adversaire en se retournant en courant. Courir puis Stick directionnel dans la direction opposée + Z.</p>
          <p style="text-align: justify;">A la suite d'un grab, le joueur a la possibilité de taper et de jeter son adversaire :</p>
          <p style="text-align: justify;">• <em>Attaque durant un grab</em>&nbsp;: Pummel<br />
          • <em>Jet avant</em>&nbsp;: Forward Throw = Fthrow<br />
          •&nbsp;<em>Jet haut</em><em>&nbsp;:&nbsp;</em>Up Throw = Uthrow<br />
          •&nbsp;<i>Jet bas</i><i>&nbsp;</i><i>:</i> Down Throw = Dthrow<br />
          •&nbsp;<i>Jet arrière</i><i>&nbsp;</i><i>:</i>&nbsp;Back Throw = Bthrow</p>
          <p style="text-align: justify;">Sortir d'un Grab consiste à faire relâcher l'emprise de l'adversaire sur vous avant que celui-ci n'ait exécuté un Throw. Lorsque vous sortez d'un grab, cela se nomme le release grab, il existe 2 formes de grab release :</p>
          <p style="text-align: justify;">•&nbsp;<em>Ground release</em>&nbsp;: Sorte de grab en restant au sol. Vous exécutez un ground release si :<br />
          - Vous chopez un adversaire dont les pieds touchent le sol lors du grab et s'il ne se débat pas avec un bouton de jump.<br />
          - Vous exécutez un pummel au moment où le grab devait se finir, et ce, quelles que soit les conditions. On nomme cela le pummel break.</p>
          <p style="text-align: justify;">•&nbsp;<em>Air release</em><em>&nbsp;</em>: Sortie de grab en exécutant une sorte de saut. Vous exécutez un Air release si :<br />
          - Vous chopez un adversaire dont les pieds ne touchent pas le sol lors du grab, et si vous n'exécutez pas un pummel break.<br />
          - Vous chopez un adversaire dont les pieds touchent le sol et celui-ci appuie sur le bouton de saut au moment où le grab prend fin (et si vous n'exécutez pas un pummel break)<br />
          - Vous chopez un adversaire sur le bord du terrain/plateforme (et si vous n'exécutez pas un pummel break), le corps du personnage adverse étant donc suspendu au-dessus du vide.</p>
          <hr />
          <p style="text-align: justify;"><strong>Meteor Smash</strong><strong>&nbsp;</strong><em>(</em><em>Smash météore</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Un smash météore est une attaque qui permet d'envoyer l'adversaire directement vers le bas (dans un angle inférieur à 45°), ce qui est très utile si exécuté en dehors du stage.&nbsp;À&nbsp;noter qu'un Meteor Smash peut être meteor cancel (contrairement au spike).&nbsp;À&nbsp;noter aussi que tous les "Spike" dans Super Smash Bros Brawl sont des Meteor Smash.</p>
          <hr />
          <p style="text-align: justify;"><strong>Meteor Canceling</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Action permettant de survivre à un smash météore en faisant un saut ou un UpB avec un certain timing.&nbsp;À&nbsp;noter que si vous voulez utiliser le meteor canceling avec les boutons de sauts (X ou Y) vous devez absolument avoir le bon timing sinon vous ne pourrez pas re-sauter avant un petit moment (ce qui causera sûrement votre mort), par contre vous ne souffrirez pas de ce problème si vous sautez avec le tap jump.</p>
          <hr />
          <p style="text-align: justify;"><strong>Stage Spike :</strong>&nbsp;Consiste à utiliser l'inclinaison du terrain pour envoyer son adversaire directement dans le vide, pour cela vous devez propulser votre adversaire sur cette inclinaison de manière à ce que celle-ci l'envoie dans le vide.</p>
          <hr />
          <p style="text-align: justify;"><strong>Range :</strong>&nbsp;Désigne la longueur, la portée d'un coup.</p>
          <hr />
          <p style="text-align: justify;"><strong>Tech Chasing</strong><strong>&nbsp;:</strong>&nbsp;Lorsque vous attaquez votre adversaire et le projetez au sol, celui-ci a 2 possibilités d'action :</p>
          <p style="text-align: justify;">•&nbsp;<em>Se laisser tomber au sol.</em></p>
          <p style="text-align: justify;">•&nbsp;<em>Exécuter un Teching. Lorsqu'il exécute un Teching au sol, il a 2 possibilités :</em><br />
          - Teching sur place<br />
          -&nbsp;Teching et rouler à droite/gauche (Teching roll).</p>
          <p style="text-align: justify;">Lorsqu'il se laisse tomber au sol, il a 4 possibilités :&nbsp;<br />
          - Rouler à droite/gauche.&nbsp;<br />
          -&nbsp;Rester au sol.<br />
          -&nbsp;Se relever normalement sur place.<br />
          - Se relever en attaquant.</p>
          <p style="text-align: justify;">Le <em>Tech Chasing</em> définit donc l'habileté à prédire l'une des possibilités citées ci-dessus et de punir votre adversaire en conséquence.</p>
          <hr />
          <p style="text-align: justify;"><strong>Tripping :</strong>&nbsp;Action de trébucher, vous plaçant ainsi dans une position de vulnérabilité. Un tripping s'exécute aléatoirement pendant une phase de running (1 chance sur 100), de dashing (1 chance sur 100), ou lorsque vous subissez un coup spécifique à un % précis. À noter que pour des raisons inconnues, Luigi a 1 chance sur 50 de tripping pendant une phase de dashing ou de running.<br />
          <em>Cette mécanique n'existe que dans Super Smash Bros. Brawl</em></p>
          <hr />
          <p style="text-align: justify;"><strong>Footstool</strong><strong>&nbsp;:</strong>&nbsp;Désigne l'action de prendre appui sur un autre personnage. Un footstool vous permet de gagner de la hauteur. Il agit comme un saut "supplémentaire", c'est-à-dire que si vous avez encore votre double saut au moment où vous effectuez le footstool, vous pouvez toujours exécuter votre double saut plus tard. Même système si vous avez déjà exécuté votre double saut, vous pouvez toujours effectuer un footstool. Exécuter celui-ci peut avoir 2 effets :</p>
          <p style="text-align: justify;">• Soit vous prenez directement une impulsion sur un personnage et celui-ci aura une phase d'étourdissement puis se retrouvera incapable d'exécuter une action (ceci peut vous être fatal si vous êtes dans le vide au moment où vous vous faites footstool).</p>
          <p style="text-align: justify;">• Soit vous avez l'animation du footstool mais cela n'a aucune incidence sur le joueur que vous étiez censé footstool. Mais ceci reste plutôt rare.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Appuyer sur X / Y au moment où vous êtes juste au-dessus d'un personnage.</p>
          <hr />
          <p style="text-align: justify;"><strong>Dashing</strong><strong>&nbsp;:</strong>&nbsp;Désigne l'accélération de votre personnage pour commencer une course.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Donner un coup sec sur le stick directionnel pour enclencher un dash.</p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Dashing Dashing</strong><strong style="text-align: justify;">&nbsp;:</strong><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Désigne l'action de ne se déplacer qu'avec des dash imput. Permet d'aller plus vite avec certains personnages qu'en courant.&nbsp;</span></p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Appuyer plusieurs fois sur le stick avant avec un certain timing de sorte à ne faire que le début du dash plusieurs fois.</p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Dashing Dancing</strong><strong style="text-align: justify;">&nbsp;:</strong><span style="text-align: justify;">Consiste à exécuter une série de dash de droite à gauche de sorte à ce que votre personnage pivote plusieurs fois sur lui-même à grande vitesse. Peut permettre de surprendre en utilisant suite à cela un <em>Dash attack Cancel</em>, un grab, un <em>Stuer Stepping</em>, <em>Back Stepping</em>, etc.</span><span style="text-align: justify;">&nbsp;</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Donner des coups secs de gauche à droite avec un certain timing sur votre stick directionnel.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Spamtiming</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Fait d'utiliser plusieurs fois et de manière répétée la même attaque.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Camping</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Technique de jeu consistant à maintenir au maximum l'adversaire à distance en lui mettant la pression (avec des projectiles le plus souvent) pour le forcer à approcher vous laissant ainsi l'initiative de l'assaut.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Stalling</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Acte délibéré qui a pour but d'éviter toute forme de conflit et de faire passer le temps afin de gagner grâce à celui-ci, rendant ainsi la partie injouable. Le stalling est interdit en compétition. À noter que le Camping et le Spamtiming ne sont pas du Stalling.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Spacing</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Fait de se mettre à une certaine distance de l'adversaire et ainsi utiliser le maximum de votre range pour maximiser vos chances d'attaquer et limiter le plus possible celles de l'adversaire (que ça soit pour une attaque, une contre-attaque ou un shieldgrab).</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Combo</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Un véritable combo est une succession de coups donnés sur la hitstun de l'adversaire et il est donc impossible d'y échapper. (Pour le vérifier, cette succession de coups est censée faire augmenter votre score en Training Mode). On utilise aussi souvent ce terme pour désigner une succession coups assénés en faisant preuve mindgame.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Wall Clinging</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Permet de sauter sur un mur et de s'y coller pendant un certain laps de temps. À noter que vous pouvez Wall Jumping après un Wall Clinging. </span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur le stick directionnel en direction du mur une fois que vous avez touché celui-ci, appuyer sur n'importe quelle touche pour annuler le Wall Clinging.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Liste des personnages pouvant utiliser le Wall Clinging (tous jeux confondus) :</em><span style="text-align: justify;">&nbsp;Carapuce,&nbsp;</span><span style="text-align: justify;">Diddy Kong, Lucario, Sheik</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Wall Jumping</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Permet de prendre appui sur le mur pour se donner une impulsion dans le sens inverse et aller plus haut.&nbsp;</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur la direction opposée au mur au moment où vous le touchez.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Liste des personnages pouvant utiliser le Wall Jumping (tous jeux confondus) :</em><span style="text-align: justify;">&nbsp;Captain Falcon, Carapuce, Diddy Kong, Falco, Fox, Lucario, Mario, Pikachu, Samus, Sonic, Toon Link, Wolf, Zero Suit Samus</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Shine</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Autre nom donné au bouclier (DownB) de Wolf, Falco et Fox.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Floating</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Désigne la flotaison de Peach, cela lui permet de flotter dans les airs et ainsi d'attaquer plusieurs fois tout en restant au-dessus du sol ou même simplement de revenir sur le terrain plus facilement. Vous ne pouvez utiliser le Floating que pendant une durée limitée (au bout d'un certain temps elle retombe toute seule) et une seule fois par phase aérienne. Vous devez donc retoucher le sol avant de pouvoir réutiliser le Floating (Contrairement au Jump le fait de s'accrocher au bord ne vous redonne pas votre Floating). Peut être utilisé pendant le 1er saut, le 2ème saut ou pendant une chute.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur la touche haut et la maintenir enfoncée (Si vous êtes au sol et que vous appuyez sur bas avant de sauter et maintenir le bouton de saut, vous flotterez à ras le sol).</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Out of Shield</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Permet de sauter (et ainsi avoir la possibilité d'exécuter une attaque aérienne) à partir du shield.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur le bouton de saut pendant un shield.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">À noter que si le Tap Jump est activé vous pouvez faire un Bup ou Usmash Out of Shield.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur Haut + B ou Haut + A pendant un shield.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">À noter également que vous pouvez effectuer un Usmash Out of Shield avec le Tap Jump désactivé.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur Y/X + Haut + A pendant un shield.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Bat Reflector</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Avec Ness ou Lucas, frapper un projectile avec le tipper de la batte (Smash avant) permet de le renvoyer.&nbsp;</span><span style="text-align: justify;">À noter que dans le cas de Ness, le projectile est renvoyé avec 2 fois plus de puissance.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Chain-Grab</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Consiste à graber et à éjecter un adversaire de manière à le re-graber sans qu'il ne puisse réagir entre les grab. Un chain-grab prend fin à un certain moment selon le pourcentage de l'adversaire ou la situation dans laquelle il se trouve. Le chain-grab est spécifique à certains personnages et sur certains personnages.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Infinite Grab</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Variante du <em>Chain-Grab</em> à la seule exception près qu'il peut être exécuté de manière infinite sans considération du pourcentage de l'adversaire ou de la situation dans laquelle il se trouve. Tous les Infinite Grabs sauf celui des Ice Climbers sont aussi appelés <em>standing infinites</em>. Le standing infinite est banni en compétition.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Wall infinite</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Action d'enchaîner un ennemi sur un mur de façon à ce qu'il ne puisse rien faire.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Wall-recover</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Action d'exécuter un <em>Wall Jumping</em> avec un <em>Teching</em>. À noter que tous les personnages peuvent wall-recover même si à la base ils n'ont pas de Wall Jumping.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur le bouton de saut juste après un Teching.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Teching</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Lorsque vous heurtez une surface dure, vous pouvez vous stopper dessus et ainsi annuler votre knockback.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyez sur R, L ou Z au moment où vous heurtez une surface dure (nécessite un timing spécifique).</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Tether Recovery</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Désigne un coup possédant des hitbox disjointes qui permet de s'accrocher directement au bord pendant une phase de recovery ou de offstage</span><span style="text-align: justify;">.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Personnages ayant des Tether Recovery</em><em style="text-align: justify;">&nbsp;:</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Herbizarre (Bup), Link (Zair), Lucas (Zair), Olimar (Bup), Samus (Zair), Sheik (Bside), Toon Link (Zair), Zero Suit Samus (Bside, Bup).</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Helpless</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Certaines attaques vous mettent en situation helpless lorsque vous les effectuez en l'air. Le helpless est un statut pendant lequel votre personnage clignote et où vous ne pouvez plus attaquer ni défendre, vous pouvez seulement influencer votre trajectoire de descente. Le helpless prend fin lorsque vous touchez le sol, vous faites toucher (sauf par une attaque qui n'inflige pas de hitstun), ou vous accrochez au rebord.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Recovery</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Désigne les actions qu'effectuent un joueur pour remonter sur le terrain lorsque celui-ci est <em>Offstage</em>. Le meilleur moyen de recovery étant d'utiliser un <em>recovery move</em>.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Recovery move</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Désigne un ou plusieurs coups d'un personnage lui permettant de revenir sur le terrain avec plus d'efficacité que ses autres coups. Plus clairement un recovery move vous donne une impulsion horizontale et/ou verticale (selon les personnages) vous permettant ainsi de revenir sur le terrain. Il est donc primordial de connaître au maximum les caractéristiques de ses recovery moves pour s'assurer une meilleure survie. À noter que le plus souvent un recovery move vous place en statut&nbsp;<em>Helpless</em>.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Offstage</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Désigne de manière générale le moment où vous vous trouvez en dehors du stage. A ne pas confondre avec les phases de Recovery, vous pouvez être en phase de offstage sans être en phase de recovery par exemple pendant un <em>Wall of Pain</em>.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Z-catch</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Consiste à attraper un objet avec le bouton de grab. Ceci est le moyen le plus rapide d'attraper un objet et de réagir juste après mais il nécessite un timing très serré si c'est l'ennemi qui vous a lancé un objet dessus.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyer sur Z lorsque l'on est en l'air au moment où l'on rentre en contact avec l'objet.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Z-Drop</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Le Z-Drop est une technique qui consiste à lancer un item et enchainer avec votre chope dans les airs afin que celui-ci tombe au sol sans être immédiatement détruit comme cela devrait normalement être le cas. Cela fonctionne par exemple avec les bombes de Link ou les fruits de Pac-Man.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Dodge Grab</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Consiste à attraper un objet avec un airdodge. À noter que votre airdodge continuera tout de même lorsque vous aurez l'objet en main mais permet de ne pas prendre trop de risque si c'est l'ennemi qui vous a lancé un objet dessus. (Le Dodge Grab peut être combiné au <em>Airdodge Cancel Throw</em> pour plus d'efficacité.).</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Comment utiliser :</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Appuyez sur R ou L lorsque vous êtes en l'air au moment où vous rentrez en contact avec l'objet.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Slipping Attack Feinte</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Technique qui consiste à feinter son adversaire en courant dans le vide pour au final revenir en effectuant une attaque (le plus souvent un Back Air).</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Turret Fighting</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Désigne un style de jeu qui consiste à utiliser au maximum ses projectiles tout en restant à portée d'attaque de l'adversaire, vous permettant ainsi de profiter un minimum du hitstun de votre adversaire par votre projectile pour lui asséner un autre coup par la suite. A combiner avec le Missil-cancelling pour une efficacité optimale.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Wall of Pain</strong><strong style="text-align: justify;">&nbsp;</strong><em style="text-align: justify;">(WoP)</em><strong style="text-align: justify;">&nbsp;:</strong><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Désigne un edgeguard pendant le lequel vous tapez votre adversaire avec une seutile série de coups lorsqu'il est hors du stage pour le propulser le plus loin possible du bord afin qu'il ne puisse pas revenir avec son recovery move.&nbsp;</span><span style="text-align: justify;">À</span><span style="text-align: justify;">&nbsp;combiner avec l'edge-hogging pour plus d'efficacité.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Gimp</strong><strong style="text-align: justify;">&nbsp;:</strong><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Consiste à tuer son adversaire à assez bas pourcentage, le plus souvent grâce à un <em>edgeguard</em>.</span></p>
          <hr />
          <p style="text-align: justify;"><strong>Lock&nbsp;</strong><strong>:</strong>&nbsp;: Désigne une situation dans laquelle votre adversaire est dans l'incapacité de se défendre ou de contre attaquer pendant une série d'un même coup. Pour créer le lock vous devez exécuter l'un des coups ci-dessous lorsque votre adversaire s'écrase au sol et n'a ni Tech, ni roulé, ni attaqué, ne s'est pas relevé après s'être écrasé au sol (<em>voir Tech Chase</em>). À noter que la seule chose que vous pouvez faire pendant un lock est d'exécuter une TDI/SDI. Liste des différents locks possible :</p>
          <p style="text-align: justify;">•&nbsp;<em>Jab Lock</em>&nbsp;(Possible avec certains personnages) : Désigne un lock effectué avec une multude de Jabs. Vous devez toucher avec seulement le 1er hit du Jab (<em>Jab Cancel</em>) pour réussir le lock. Un Jab lock prend fin lorsque vous stoppez ou ratez celui-ci ou lorsque votre adversaire sort du terrain (le Jab lock faisant glisser petit à petit vers le bord du terrain.). À noter que contrairement à la <em>techchase</em> la relevée d'un jab lock après que celui-ci soit arrêté se fait sans autre choix que de se redresser normalement sans attaquer, plaçant ainsi le personnage qui se relève en grosse position de vulnérabilité.</p>
          <p style="text-align: justify;">•&nbsp;<em>Laser/Arrow/... lock</em><em>&nbsp;</em>(possible avec le Bneutre de Falco/Ice Climbers/Link/Toon Link/Luigi /Mario) : Désigne un lock effectué avec une multude de lasers ou de glaçons (Pour que votre Ice lock soit continu il faut que vos Ice Climbers soit désynchronisés.). Un Laser/Ice/... lock prend fin lorsque vous stoppez celui-ci ou lorsque votre adversaire sort du terrain (le Laser/Ice lock faisant glisser petit à petit vers le bord du terrain.). Pour la relevée c'est le même principe que le <em>Jab lock</em>.</p>
          <p style="text-align: justify;">•&nbsp;<i>Down Tilt lock</i><i>&nbsp;</i>: Il existe 2 sortes de Dtilt lock, ceux se faisant selon la règle des lock (définie plus haut) qu'on appellera True Dtilt locks et ceux qui se font d'une autre façon que la règle citée ci-dessus que l'on nommera False Dtilt locks.</p>
          <p style="text-align: justify;">- True Dtilt lock (Metaknight / Lucas / R.O.B) : même principe et caractérisques que le jab lock.</p>
          <p style="text-align: justify;">- False Dtilt lock (Ness / Lucas / Zelda) : Ici le but est d'effectuer un 2eme Dtilt avant que la hitstun de votre adversaire ne soit terminée, l'empêchant ainsi d'attaquer/se défendre/ect. Il faut donc exécuter le 1er Dtilt à partir d'un certain % afin que celui-ci donne assez de hitstun à votre adversaire, de telle sorte que ce hitstun ne soit toujours pas terminé lorsque le 2e Dtilt le touchera. Le seul moyen de sortir de ce Dtilt lock est d'effectuer une TDI/SDI en dehors de la portée du Dtilt ou alors que le joueur arrête de faire des Dtilt.</p>
          <p style="text-align: justify;">•&nbsp;<i>Bananas lock</i><i>&nbsp;</i>: Possible avec les bananes de Diddy Kong, le système est à peu près le même que celui du False Dtilt lock. Le but est donc de toucher votre adversaire avec la 2ème banane sur la hitstun de la 1ère banane. Pour sortir d'un bananas lock vous devez soit attendre de tomber du terrain, soit attendre que le joueur qui a effectué le bananas lock rate son timing, vous permettant ainsi de rebouger librement.</p>
          <h2 class="redac" style="text-align: justify;">Notions essentielles</h2>
          <p style="text-align: justify;"><strong>Hurtbox</strong><strong>&nbsp;</strong><strong>:</strong> Définit la zone où votre personnage peut se faire toucher. Si une hitbox rentre en contact avec votre hurtbox vous serez touché. La hurtbox représente le corps de votre personnage (sauf dans le cas de Donkey Kong où sa hurtbox est plus grosse que son corps lui même). À noter que certains items ou décors d'un terrain peuvent contenir une hurtbox et que vous pouvez ainsi interagir avec eux (par exemple la moto de Wario ou les Maskass de Yoshi Island).</p>
          <hr />
          <p style="text-align: justify;"><strong>Hitbox&nbsp;</strong><em>(Zone de frappe)</em><strong>&nbsp;:</strong>&nbsp;Définit la zone d'action d'une attaque. À noter que lorsque votre Hitbox rentre en contact avec la Hurtbox de l'adversaire cela lui inflige des dégats. À noter aussi que les hitbox contiennent la plupart du temps une hurtbox (Sauf dans le cas des Disjointed Hitbox).</p>
          <hr />
          <p style="text-align: justify;"><strong>Disjointed Hitbox</strong><strong>&nbsp;</strong><em>(</em><em>Zone de frappe disjointe</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Ce terme est utilisé pour désigner une hitbox ne contenant pas de hurtbox. Ainsi si l'adversaire touche cette hitbox vous ne subirez pas de dégât. Quelques exemples de hitbox disjointes visibles : Les épées des personnages de Zelda ou Fire Emblem, le yoyo de Ness, la tornade de Meta Knight, etc. D'autres hitbox disjointes peuvent être invisibles : Le Utilt et le Ftilt de Snake dans Super Smash Bros Brawl.</p>
          <hr />
          <p style="text-align: justify;"><strong>Sweetspot</strong><strong>&nbsp;</strong><strong>:</strong> Désigne une partie précise de la hitbox d'une attaque qui touche une partie précise de la hurtbox de l'adversaire (on parle ici de situation d'attaque) et qui a pour conséquence de faire plus de dégâts / knockback que les autres situations d'attaque. Certaines attaques ont des sweetspot plus remarquables que d'autres, on retiendra l'exemple du Bair et Fair de Zelda, de l'épée de Marth (Tipper), du Fair de CaptainFalcon, du Bair et Fsmash de Ness et du Usmash de Peach.</p>
          <hr />
          <p style="text-align: justify;"><strong>Tipper</strong><strong>&nbsp;</strong><strong>:</strong> Nom donné au sweetspot de l'épée de Marth ou de la batte de Ness.</p>
          <hr />
          <p style="text-align: justify;"><strong>Mindgame</strong><strong>&nbsp;</strong><strong>:</strong> C'est la vision de jeu d'un joueur et sa faculté à anticiper une action de l'adversaire afin d'éviter celle-ci ou punir l'ennemi.</p>
          <hr />
          <p style="text-align: justify;"><strong>Gameplay</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Définit en général l'ensemble des mouvements et des techniques d'un personnage.</p>
          <hr />
          <p style="text-align: justify;"><strong>Playstyle&nbsp;</strong><strong>:</strong>&nbsp;Définit de façon générale le style de jeu d'un joueur avec son personnage.</p>
          <hr />
          <p style="text-align: justify;"><strong>Metagame</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Définit l'évolution globale des techniques d'un personnage ou de ce qui se joue à niveau compétitif à une période donnée.</p>
          <hr />
          <p style="text-align: justify;"><strong>Fast-Falling</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Permet d'accélérer votre vitesse de chute lorsque vous êtes en l'air. Appuyer sur bas (et rester appuyer) au plus haut d'un saut, après une attaque aérienne ou après un UpB.</p>
          <hr />
          <p style="text-align: justify;"><strong>Tumble</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Désigne la 2eme partie d'une phase du knockback, le Tumble désigne la phase où vous pouvez commencer à effectuer des actions.</p>
          <hr />
          <p style="text-align: justify;"><strong>Decaying Attack</strong><strong>&nbsp;</strong><em>(Attack Decay)</em><strong>&nbsp;:</strong>&nbsp;Aussi connue sous d'autres noms (Diminished Return / Move Decay / Damage Decay); désigne l'affaiblissement des attaques. A chaque fois que vous exécutez une attaque celle-ci est ajoutée à une liste invisible (appelée liste d'attente). Cette liste répertorie les 10 dernières attaques que vous avez effectuées et plus une même attaque apparaît dans votre file d'attente, plus elle s'affaiblit (c'est-à-dire que les % et le knockback de cette attaque sont réduits).</p>
          <p style="text-align: justify;">Ainsi :</p>
          <p style="text-align: justify;">• Votre coup sera le plus puissant possible lorsqu'il n'est pas dans la liste, on dit que ce coup est le plus frais possible (le "Freshest").</p>
          <p style="text-align: justify;">• Votre coup sera le moins puissant possible lorsqu'il apparaît 10 fois dans la liste, on dit que ce coup est le plus affaibli possible (le "Stallest").</p>
          <p style="text-align: justify;">À noter que l'ordre dans lequel les attaques apparaissent dans la liste a une influence sur l'affaiblissement d'une attaque.&nbsp;Pour remédier au Decaying Attack sur un ou plusieurs coup il existe plusieurs méthodes :</p>
          <p style="text-align: justify;">•&nbsp;<em>Mourir :</em>&nbsp;Lorsque vous mourrez, votre liste d'attente est remise à 0, rendant ainsi chacun de vos coups totalement frais.</p>
          <p style="text-align: justify;">•&nbsp;<em>Exécuter d'autres attaques :</em>&nbsp;Si vous voulez rendre un coup plus frais, exécutez un nombre suffisant d'autres actions pour faire en sorte que l'attaque que vous voulez rendre plus "fraîche" apparaisse le moins de fois possible dans votre liste d'attente.</p>
          <p style="text-align: justify;">•&nbsp;<em>Se transformer :</em>&nbsp;Si votre personnage a la possibilité de se transformer (Zelda/Sheik, Carapuce/Herbizarre/Dracaufeu, Samus/Zero Suit) il remet sa liste d'attente à 0 à chaque transformation, rendant ainsi chacun de vos coups totalement frais. Cette possibilité existe uniquement dans Melee et Brawl.</p>
          <p style="text-align: justify;">Pour qu'une attaque soit prise en compte dans la liste d'attente elle doit toucher une hurtbox. Donc si vous faites une attaque dans le vide ou sur un bouclier elle ne sera pas prise en compte dans la liste d'attente.</p>
          <hr />
          <p style="text-align: justify;"><strong>Blastzone</strong><strong>&nbsp;</strong><em>(hors limite</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Définit la zone qui se situe en dehors de l'écran (vous ne voyez plus votre personnage). Si votre personnage se situe dans cette zone vous le verrez apparaître dans une loupe vous indiquant sa position. À noter qu'un personnage si situant dans la blastzone tombera plus vite qu'à la normale. À noter aussi que si votre personnage reste trop longtemps dans la blastzone, il subira des dégâts.</p>
          <hr />
          <p style="text-align: justify;"><strong>Hitlag</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Définit l'interaction entre une Hitbox et une Hurtbox. Cela a pour effet de créer un "freeze" de cette interaction (la durée de celui-ci dépendant de la puissance du coup portant la hitbox). Pendant le hitlag vous ne pouvez exécuter aucune action. À noter que les attaques projectiles ne vous infligent pas de hitlag si vous en êtes l'auteur. À noter aussi que pendant toute la durée du hitlag vos frames de hitbox sont toujours actives, ainsi si un adversaire vous fonce dessus pendant le hitlag il subira lui aussi le coup à l'origine de celui-ci. Enfin, pendant le hitlag il vous est possible de SDI/TDI (c'est grâce à cela que vous pouvez sortir des multihits).</p>
          <hr />
          <p style="text-align: justify;"><strong>Shield Hitlag</strong><strong>&nbsp;</strong><strong>:</strong> Même définition que le Hit Lag mais désigne cette fois-ci l'interaction entre une Hitbox et un bouclier. A la fin du Shield Hitlag commence la Shieldstun pour celui qui était en train de shield.</p>
          <hr />
          <p style="text-align: justify;"><strong>Shieldstun</strong><strong>&nbsp;</strong><em>(</em><em>ou Shield Hit Stun</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Prend effet après le Shield Hitlag, le shieldstun désigne le temps durant lequel l'on ne peut pas sortir de son bouclier (après le Shield Hitlag). À noter que le Shieldstun est entièrement dépendant des dégâts de l'attaque qui a touché votre bouclier. Ainsi plus une attaque qui fait des % touche votre bouclier, plus votre shieldstun sera long. Mais cette règle ne s'applique pas pour les Specials qui ont chacun un shieldstun propre non dépendant du pourcentage. À noter que pendant le shieldstun vous ne pourrez pas utiliser le buffering car celui-ci sera compté comme une SDI/TDI.</p>
          <hr />
          <p style="text-align: justify;"><strong>Autocancelling Aerials</strong><strong>&nbsp;</strong><em>(</em><em>attaques aériennes annulées</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Définit le moment où une attaque aérienne s'annule à la retombée au sol, plaçant le personnage dans une position debout neutre (annulation du cooldown) lui permettant d'exécuter n'importe quelle nouvelle action dans l'immédiat. À noter que seules certaines attaques aériennes peuvent être autocancel et elles ont chacune un timing spécifique.</p>
          <hr />
          <p style="text-align: justify;"><strong>Edge-guarding</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à empêcher un ennemi de revenir sur le terrain en utilisant différentes actions et en profitant au maximum des faiblesses de la recovery de son adversaire.</p>
          <hr />
          <p style="text-align: justify;"><strong>Edge-hogging</strong><strong>&nbsp;</strong><em>(</em><em>monopolisation du bord</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Action de s'accrocher sur le bord pour empêcher votre adversaire de faire de même (2 personnages ne pouvant pas s'accrocher en même temps sur les 3 premiers volets de la série) en profitant ou non de ses frames d'invincibilité. Le edgehogging est une forme d'edgeguarding.</p>
          <hr />
          <p style="text-align: justify;"><strong>Tether Hogging</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à exécuter un edge-hogging contre un personnage utilisant des tether recovery. En effet il est plus facile de gimp un personnage utilisant des tether recovery avec un edge-hogg car celles-ci touchent le personnage lors de son d'edge-hogg mais pas le bord lui-même. Comme la tether recovery est une hitbox disjointe et que seul le contact entre l'edge et la hurtbox du personnage permet de s'accrocher à celui-ci, cela limite très fortement les possibilités du personnage à remonter sur le terrain.</p>
          <hr />
          <p style="text-align: justify;"><strong>Hugging / Speed Hugging</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Action de s'accrocher directement au bord à partir du terrain. Technique utilisée le plus souvent pour l'edge-hogging.</p>
          <p style="text-align: justify;">#&nbsp;<em>Comment utiliser</em>&nbsp;:</p>
          <p style="text-align: justify;">•&nbsp;<em>Hugging</em><em>&nbsp;</em>: Si votre personnage vous le permet : Courez dans la direction du bord et une fois que votre personnage est sorti du terrain maintenez la direction opposée à celle dans laquelle vous couriez.</p>
          <p style="text-align: justify;">•&nbsp;<i>Speed Hugging</i><i>&nbsp;</i>: Avec tous les personnages : Courez dans la direction du bord et une fois que votre personnage est sorti du terrain faites un quart de cercle partant du bas jusqu'à la direction opposée de celle dans laquelle vous couriez.</p>
          <hr />
          <p style="text-align: justify;"><strong>Edge-hopping</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Presser bas (ou côté) et sauter tout de suite après à partir du bord d'une plate-forme pour revenir plus vite sur le stage qu'en appuyant sur X ou Y. À noter que cette action utilise votre second saut. À noter aussi que certains personnages ne sautent pas assez haut pour effectuer certaines de leurs attaques aériennes en utilisant cette action.</p>
          <hr />
          <p style="text-align: justify;"><strong>Knockback</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Définit la vitesse de recul/de projection d'une attaque. Plus vous avez de %, plus votre knockback sera grand (donc plus vous serez éjecté loin). Le knockback possède 2 phases : La phase de <em>Hitstun</em> et la phase de <em>Tumble</em>.</p>
          <hr />
          <p style="text-align: justify;"><strong>Hitstun</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;1ère phase du knockback. Définit la durée de l'étourdissement que vous subissez après un coup. Pendant le hitstun vous ne pouvez exécuter aucune action jusqu'à rentrer en phase de <em>Tumble</em>. À noter que plus vous avez de dégâts, plus la durée du hitstun sera grande. À noter aussi que certains coups n'infligent pas de hitstun comme le Bcôté et Bbas de Mario, le Bneutre de Fox, le Bneutre (chargé à fond) de Carapuce (dans Brawl).</p>
          <hr />
          <p style="text-align: justify;"><strong>Perfect Shield</strong><strong>&nbsp;</strong><em>(</em><em>Bouclier parfait</em><em>)</em><strong>&nbsp;:</strong>&nbsp;Réaliser un perfect shield (aussi appelé Power Shield) vous permera d'annuler les temps de lag (Shieldstun) pour sortir du bouclier et ainsi contre-attaquer de la manière la plus rapide possible. À noter qu'un perfect shield n'usera pas votre bouclier et ne vous repoussera pas comme un shield classique. Pour réussir cette technique il faut activer le bouclier au moment même de l'impact d'une attaque.</p>
          <hr />
          <p style="text-align: justify;"><strong>Super Armor</strong><strong>&nbsp;</strong><em>(</em><em>Super Armure</em><em>)</em><strong>&nbsp;:</strong>&nbsp;La super armor (SA) est un état où lors d'une attaque, tout coup infligé au titulaire de la super armor ne lui causera pas de knockback, permettant ainsi à l'attaque entamée par celui-ci de continuer. À noter que même si le knockback est annulé, les dommages sont tout de même infligés au titulaire de la super armor.</p>
          <hr />
          <p style="text-align: justify;"><strong>Frame data</strong><strong>&nbsp;:</strong>&nbsp;Permet de distinguer toute les phases d'une attaque en l'analysant frame par frame. On distingue plusieurs phases pendant une attaque :</p>
          <p style="text-align: justify;">•&nbsp;<em>Startup&nbsp;</em>: Désigne le nombre de frames que met l'attaque pour commencer, pendant les frames de startup, l'attaque n'a aucun effet.</p>
          <p style="text-align: justify;">•&nbsp;<em>Hitbox</em><em>&nbsp;</em>: Désigne la/les frame(s) pendant la(les)quelle(s) l'attaque est effective/touche.&nbsp;</p>
          <p style="text-align: justify;">•&nbsp;<em>Cooldown&nbsp;</em>: Désigne le nombre de frames pendant lesquelles vous êtes vulnérable et ne pouvez exécuter aucune action après votre frame de Hitbox.</p>
          <p style="text-align: justify;">•&nbsp;<em>IASA (Interruptable As Soon As)</em><em>&nbsp;</em>: Désigne la première frame où l'on peut agir de nouveau après une attaque.</p>
          <hr />
          <p style="text-align: justify;"><strong>Directional Influence (DI)</strong><strong>&nbsp;:</strong>&nbsp;Définit l'habileté à contrôler sa trajectoire après un coup. Cela vous permet entre autres de survivre à de plus hauts % et d'éviter des attaques. Afin de réaliser la meilleure DI possible : Orientez votre stick directionnel dans la direction perpendiculaire à votre trajectoire d'éjection (knockback) pendant le hitlag, effectuez ensuite votre attaque aérienne la plus rapide (ou Z-air si vous en avez un et s'il est plus rapide que vos aerials) ou lancez un item dès que possible pour sortir de votre hitstun (lorsque vous rentrez en phase de <em>Tumble</em>), faites un <em>fastfall</em>, puis sautez (s'il s'agit d'une DI horizontale) et exécutez un <em>momentum canceling</em> si vous en possédez un. À noter qu'il est très peu recommandé d'exécuter des mouvements spéciaux pendant votre Tumble car ceux-ci ont tendance à vous donner un effet de "boost", rallongeant ainsi votre knockback et augmentant vos chances de mourir au lieu de les réduire. Il existe cependant des exceptions avec des spéciaux qui sont des <em>momentum reset</em>.</p>
          <p style="text-align: justify;">Dans Smash 4 et seulement dans cet opus (3DS &amp; Wii U), l'orientation du stick ne se fait pas perpendiculairement. Les joueurs peuvent diminuer le knockback d'une attaque reçue et échapper de certains combos en appuyant sur la direction opposée à celle dans laquelle ils sont envoyés, et ce, en synchronisation avec l'attaque reçue. Comme ce système repose sur un principe similaire à celui de vecteurs de force, certain préfèrent appeler cette technique <strong><em>Vectoring</em></strong>, <em>vectorial influence</em> ou encore <em>knockback influence</em>.<br />
          <strong>UPDATE : Il semblerait que le Vectoring ait été enlevé lors de la mise à jour 1.0.4 pour repasser sur de la DI classique comme dans les précédents opus.</strong></p>
          <hr />
          <p style="text-align: justify;"><strong>Vectoring</strong><strong>&nbsp;:</strong>&nbsp;Autre nom donné au principe de Directional Influence exclusif à Super Smash Bros 3DS &amp; Wii U. Certains lui préfèrent le nom de vectorial influence ou knockback influence, tandis que d'autres considèrent que garder le nom de directional influence pour parler de cette mécanique est plus pertinent. Retrouvez notre <a href="http://www.eclypsia.com/fr/ssb-3ds/guides/tuto635.html">guide sur le Vectoring</a> pour plus de précisions à ce sujet.</p>
          <p style="text-align: justify;"><strong>UPDATE : Il semblerait que le Vectoring ait été enlevé lors de la mise à jour 1.0.4 pour repasser sur de la DI classique comme dans les précédents opus.</strong></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Projo Priority</strong><strong style="text-align: justify;">&nbsp;:</strong><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Une attaque projectile définit une attaque qui ne donnera pas de <em>Hitlag</em> (ou <em>Shield Hitlag</em>) à votre personnage lorsque celle-ci touche. Il existe différentes catégories d'attaques projectile et il existe des priorités entre chacune des catégories :</span></p>
          <p style="text-align: justify;">•&nbsp;<em>Non-projectiles</em>&nbsp;(ne peut pas être renvoyé par un réflecteur) : DownB de Mr. Game &amp; Watch, DownB de Falco, Bcôté de Zelda, Bneutre de Ness/Lucas, Bcôté de King Dedede, un lancé de personnage sur vous.</p>
          <p style="text-align: justify;">•&nbsp;<em>Projectiles Vivants</em>&nbsp;(possèdent une Hurtbox et une Hitbox et stoppent les projectiles Lasers et les autres projectiles vivants) : : DownB de Link/Toon Link, Bneutre des Ice Climbers, Bcôté de Wario, DownB de R.O.B., Bcoté d'Olimar, Bneutre de Snake, Bcôté de Snake.</p>
          <p style="text-align: justify;">•&nbsp;<em>Projectiles Lasers</em>&nbsp;(ils passent à travers les hitboxs, tapent les hurtboxs de projectiles et stoppent les projectiles vivants) : Bneutre de Fox/Falco, Bneutre de Sheik, DownB de Diddy Kong, Bcôté de Lucas, DownB des Ice Climbers, Bcôté de Herbizarre.</p>
          <p style="text-align: justify;">•&nbsp;<em>Projectiles Supers</em>&nbsp;(ce sont des projectiles Laser qui ne sont pas détruits par des projectiles vivants) : Bneutre de R.O.B., Bcôté de Ness, Bup de Ness/Lucas, Bneutre de Ness, Bneutre de Pikachu.</p>
          <p style="text-align: justify;">•&nbsp;<em>Projectiles de Zone</em>&nbsp;(ils s'entrechoquent avec des hitbox de projectiles, tapent et passent à travers les hurtbox de projectiles mais n'interagissent pas avec les Lasers) : Bneutre de Bowser/Dracaufeu, Bcôté (explosion) de Zelda, Bup de Lucas, Bneutre de Kirby/King Dedede, Bcôté de Lucario (qui ne chope pas).</p>
          <p style="text-align: justify;">•&nbsp;<em>Projectiles Fantômes</em>&nbsp;(ils n'ont aucune interaction avec les autres projectiles) : DownB de Samus.</p>
          <p style="text-align: justify;">•&nbsp;<em>Projectiles Fragiles</em>&nbsp;(ils sont détruits par tous les autres types de projectiles et cassent seulement d'autres projectiles fragiles) : Bneutre de Diddy Kong.</p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Smash DI / Tap DI (SDI / TDI)</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Définit l'habileté à influencer votre trajectoire à l'intérieur des multihits et le plus souvent vous permet d'en sortir.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Tap DI</em><em style="text-align: justify;">&nbsp;:</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Orienter le stick directionnel dans la direction de votre choix (la plus utile selon la situation et le multihit en vigueur) et répéter l'action autant de fois que possible jusqu'à ce que le multihit soit terminé ou que vous en soyez sorti. À noter que pour la Tap DI vous n'avez pas besoin de revenir à la position initiale du stick directionnel (Position 0) et vous pouvez donc donner plus d'efficacité à votre TDI en effectuant des petits arcs de cercle avec votre stick directionnel.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">Par exemple pour une TDI vers le haut, au lieu de faire : (TDI haut &lt; Position 0 &lt; TDI haut) x * , effectuez des pettis arcs de cercle vers le haut sans revenir à la position 0 avec par exemple : (TDI haut &lt; TDI haut-droite &lt; TDI haut-gauche &lt; TDI haut) x * ( «*» désignant le nombre de fois où vous répétez l'action jusqu'à ce que le multihit soit terminé ou que vous en soyez sorti).</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">• <em>Smash&nbsp;</em></span><em><em style="text-align: justify;">DI</em>&nbsp;:</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Orienter le stick C dans la direction de votre choix (la plus utile selon la situation et le multihit en vigueur) et répéter l'action autant de fois que possible jusqu'à ce que le multihit soit terminé ou que vous en soyez sorti. À noter qu'au contraire de la TDI avec le stick directionnel, pour la SDI avec le stick C vous êtes obligé de faire revenir le stick C à la position initiale (position 0) pour que celle-ci soit la plus efficace possible.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">Par exemple pour faire une SDI vers le haut vous n'avez pas d'autre choix que de faire : (SDI haut &lt; Position 0 &lt; SDI haut) x * ( «*» désignant le nombre de fois où vous répétez l'action jusqu'à ce que le multihit soit terminé ou que vous en soyez sorti).</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">Vous avez la possibilité d'effectuer soit la SDI, soit la TDI, mais effectuer les 2 ensembles rend plus optimale votre capacité à influencer votre trajectoire à l'intérieur des multihits et vous aurez donc de plus grandes chances d'en sortir.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Momentum Reset</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Un coup dit momentum reset est un coup qui a pour effet de stopper immédiatement (ou presque) votre knockback, vous permettant ainsi de survivre à des % très élevés. Il s'effectue généralement pendant une phase de Directionnal Influence, juste après avoir exécuté votre attaque aérienne la plus rapide ou après avoir lancé un item.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Ledge Grabbing</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Action de s'accrocher au bord. Lors d'un ledge grabbing vous bénéficiez d'un certain nombre de frames d'invincibilité.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Ledge Popping</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Consiste tout simplement à ne pas s'accrocher à l'edge en restant appuyé sur bas avec le stick directionnel au moment où vous passez sur la zone d'accrochage (dite zone de sweetspot de l'edge) de celui-ci.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Buffering</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Permet de rentrer une commande pendant que votre personnage est en train d'effectuer une autre action, de façon à ce que cette commande soit exécutée dès que votre personnage le pourra (tout cela avec un certain timing). Cela permet donc de rentrer des commandes à l'avance afin que l'enchaînement des actions se fasse le plus rapidement possible.</span></p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">Slot Priority</strong><strong style="text-align: justify;">&nbsp;:&nbsp;</strong><span style="text-align: justify;">Désigne les caractéristiques des ports de manette. En effet dans certaines situations ça sera le port de manette qui décidera de votre sort. Petites explications :</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Avantage du suicide</em><em style="text-align: justify;">&nbsp;:</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Lors d'une action suicide (Bside de Diddy Kong, Bside de Bowser, Bside de Ganondorf, Neutral B de Kirby, Neutral B de King Dedede, Neutral B de Wario, le Cargo (1ère partie du Fthrow) de DK) le port décide de qui va mourir en premier ou si il y a sudden death (mort subite). Par exemple avec Bowser si vous vous suicidez avec son Bside et votre port de manette est moins élevé que celui de votre adversaire, ça sera votre adversaire qui mourra le premier, et si votre port de manette est plus élevé que celui de votre adversaire, vous mourrez en même temps créant ainsi le sudden death. Par contre dans le cas du Bside de Ganondorf c'est totalement aléatoire et la disposition des ports n'a aucune influence. Même si au final tout cela n'a pas réellement d'importance car dans les règles de compétition de SSBB, c'est l'auteur de l'action suicide sur la dernière vie de l'adversaire qui est déclaré vainqueur du match quel que soit le dénouement de la partie.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Grab Priority</em><em style="text-align: justify;">&nbsp;:</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Lorsque 2 personnages essayent de se grab en même temps ou essayent de grab un autre personnage en même temps, c'est celui qui a le port de manette le moins élevé d'entre les 2 qui verra son grab pris en compte.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">False Super Armor&nbsp;</em><em style="text-align: justify;">:</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Pendant un Grab, si les 2 personnages (le grabbeur et le grabbé) se font toucher en même temps par une même hitbox, le joueur avec le port le plus élevé ne subira aucun knockback ni aucun changement d'état (Exemple : L'état glacé du Neutral B de Lucas) mais subira tout de même les dégâts qu'aurait dû lui infliger l'attaque.</span></p>
          <p style="text-align: justify;"><span style="text-align: justify;">•&nbsp;</span><em style="text-align: justify;">Transformation</em><em style="text-align: justify;">&nbsp;:</em><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">S’il y a des transformations de personnage (Zelda/Sheik, Samus/Zero Suit, Carapuce/Herbizarre/Dracaufeu) exécutées en même temps par 2 personnes ou plus, c'est celui qui a le port le plus élevé qui se transformera en premier.</span></p>
          <h2 class="redac" style="text-align: justify;">Notions avancées</h2>
          <p style="text-align: justify;">Ci-dessous sont répertoriées des techniques avancées qui étaient possibles dans Super Smash Bros. Brawl. La version 3DS/Wii U ayant une physique légèrement plus rapide mais tout de même plus proche de celle de Brawl que de celle de Melee, nous avons préféré re-lister l'ensemble des techniques et éditeront le lexique en fonction des changements.</p>
          <p style="text-align: justify;"><strong>Phantasm Stop</strong><strong>&nbsp;</strong><em>(Falco/Fox)</em><strong> :</strong> Permet de stopper un Bside de Fox ou Falco et ainsi rendre sa trajectoire plus courte.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Appuyer sur B avec un certain timing pendant le Bside.</p>
          <hr />
          <p style="text-align: justify;"><strong>Quick Dash Attack</strong><strong>&nbsp;</strong><strong>:</strong> Consiste à effectuer une dash attack pendant les premières frames du Dashing au lieu de la faire pendant un Running. Le but étant d'exécuter la dash attack plus rapidement qu'à l'ordinaire. En plus de son utilité première, cette technique est à l'origine de plusieurs autres techniques.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Dashing + C-Stick vers le Bas pendant les premières frames du dashing.</p>
          <hr />
          <p style="text-align: justify;"><strong>Reverse Aerial Rush (RAR)</strong><strong>&nbsp;</strong><strong>:</strong> Permet de se retourner pendant un running juste avant de sauter. Très pratique pour faire un Bair à n'importe quel moment.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Running puis direction inverse + X ou Y.</p>
          <hr />
          <p style="text-align: justify;"><strong>Auto-RAR</strong><strong>&nbsp;</strong><strong>:</strong> Exactement le même principe que le Reverse Aerial Rush, la différence venant juste de la façon de le faire.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> (Avoir le Spécial sur le stick C) Running puis stick C dans la direction opposée + X ou Y.</p>
          <hr />
          <p style="text-align: justify;"><strong>Glide Tossing</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à lancer un Item tout en effectuant une glissade au moment du lancer. La longueur de la glissade et le timing à avoir pour le glide tossing varient selon le personnage.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Roll + Stick C dans l'une des directions cardinales. / Ou : Roll + (A + directions cardinales avec le stick directionnel)</p>
          <hr />
          <p style="text-align: justify;"><strong>Hyphen Smash</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à effectuer un Usmash en profitant de l'impulsion de votre running ou votre dashing, vous faisant ainsi faire une glissade pendant celui-ci. La longueur de la glissade varie selon le personnage.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Running ou dashing + C stick vers le haut (Peut être chargé en maintenant Z au même moment).</p>
          <hr />
          <p style="text-align: justify;"><strong>Dash Attack Cancel Up Smash (DACUS)</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Effet similaire au Hyphen Smash avec des distances de glissade différentes de celui-ci, le but étant cette fois-ci d'annutiler sa dash attack pour exécuter un Usmash. Par contre, avec la majorité des personnages cette technique vous fera encore moins glisser qu'un hyphen smash, seuls certains personnages bénéficient d'une plus longue distance de glissade grâce à cette technique (Snake, Wolf, Falco, Rondoudou, Sheik, Wario, Link). Le timing à avoir pour le DACUS varie selon le personnage.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;QDA + (Direction haute avec le stick directionnel + Z pendant les premières frames du QDA. (Maintenir Z pour charger le Usmash et glisser plus loin selon le personnage).</p>
          <p style="text-align: justify;"><strong>UPDATE : Il semblerait que cette mécanique ait été enlevée des versions 3DS/Wii U lors de la mise à jour 1.0.4.</strong></p>
          <hr />
          <p style="text-align: justify;"><strong>Item Boosting</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Même principe qu'un DACUS avec un objet en main, le but étant de donner un effet similaire au glide tossing avec des distances de glissade différentes de celui-ci. La longueur de la glissade et le timing à avoir pour l'Item Boosting varient selon le personnage.&nbsp;</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Avoir un objet en main puis QDA + (Direction haute avec le stick directionnel + Z pendant les premières frames du QDA).</p>
          <hr />
          <p style="text-align: justify;"><strong>DLX Hit Cancel</strong><strong>&nbsp;</strong><em>(Falco/Snake)</em><strong>&nbsp;:</strong>&nbsp;Variante du DAC, permet de faire une dash attack suivi directement d'un Usmash (les 2 coups toucheront votre adversaire).</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Faire une dash-attack et au moment même où celle-ci touche un adversaire, exécuter un Usmash (nécessite un certain timing).</p>
          <hr />
          <p style="text-align: justify;"><strong>Pivot Walking</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à pivoter sur soi-même tout en continuant à marcher dans la même direction. Avec certains personnages cette technique vous permet d'accélérer votre vitesse de marche. Principalement utile pour utiliser un Smash ou un Back Stepping tout en se déplaçant et en ayant une vitesse de marche proche de celle de la course.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Maintenir A puis walking + Stick C dans la diagonale haute inverse à la direction de votre walking, le tout pendant celui-ci.</p>
          <hr />
          <p style="text-align: justify;"><strong>Grab-Boosting</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Dans le même principe que le DACUS, le but étant ici de rallonger la portée de dash grab en annulant une dash attack. Seuls certains personnages bénéficient d'une amélioration de la portée de leur dash grab grâce à cette technique.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;QDA + Z pendant les premières frames du QDA. /&nbsp;<strong>Ou :</strong> Running puis Dash Attack + Z pendant les premières frames de la dash attack.</p>
          <hr />
          <p style="text-align: justify;"><strong>Reverse Grab-Boosting</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Même principe que le Grab-Boosting, le but étant cette fois-ci de donner un effet différent que le pivot grab (avec une plus grosse portée et moins de cooldown) en annulant une dash attack pour exécuter un pivot grab. Les différences entre le Reverse Grab-Boosting et le Pivot Grab dépendent du personnage avec lequel vous jouez.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;QDA + (Stick directionnel dans la direction opposée à votre personnage + Z pendant les premières frames du QDA). / <strong>Ou :</strong> Running puis Dash Attack + (Stick directionnel dans la direction opposée à votre personnage + Z pendant les premières frames de la dash attack).</p>
          <hr />
          <p style="text-align: justify;"><strong>Stuer Stepping</strong><strong>&nbsp;</strong><strong>:</strong> Consiste à annuter un Dashing pour effectuer un Fsmash. Ceci a pour effet d'allonger la portée de votre Fsmash car vous effectuez une petite glissade juste avant celui-ci.</p>
          <p style="text-align: justify;">• <em>Comment utiliser :</em> Dashing + C-stick vers l'avant pendant les premières frames du Dashing / <strong>Ou :</strong>&nbsp;Dashing + (Stick directionnel dans la direction du dashing + A pendant les premières frames du Dashing (Maintenir A pour charger le Fsmash).</p>
          <hr />
          <p style="text-align: justify;"><strong>Back Stepping</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à annutiler un Dashing pour effectuer un Fsmash dans la direction opposée au Dashing inial, le but étant, outre le fait d'exécuter une pete glissade pour effectuer un Fsmash dans la direction inverse, de rallonger la portée du Fsmash de certains personnages tel que Ganondorf, Sonic, Captain Falcon et Mario. En effet ces 4 personnages, lorsqu'ils font un Fsmash dans la direction opposée, exécutent un pas avant celui-ci ce qui a pour effet d'en rallonger considérablement la portée.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Dashing + C-stick vers l'arrière pendant les premières frames du Dashing. / <strong>Ou :</strong> Dashing + (Stick directionnel dans la direction opposée + A pendant les premières frames du Dashing (Maintenir A pour charger le Fsmash)).</p>
          <hr />
          <p style="text-align: justify;"><strong>Grounded FootStool Comboing (GFSC)</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Lorsque vous exécutez un footstool sur un ennemi au sol, cela donne un temps de "lag" à votre adversaire alors que vous vous n'en aurez aucun mais en contrepartie le saut que vous effectuez sur l'adversaire vous propulse dans les airs vous mettant hors d'atteinte pour le punir pendant son temps de "lag". Le principe du GFSC est donc d'effectuer une attaque qui permet d'annuler le saut que vous effectuez après un Footstool au sol pour pouvoir toucher l'ennemi sur son temps de "lag".</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Sauter sur un ennemi au sol (<em>Grounded Footstool</em>) et exécuter immédiatement une attaque permettant un GFSC.</p>
          <hr />
          <p style="text-align: justify;"><strong>Edgewarpping</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Un edgewarpping consiste à annuler le helpless, et le cooldown du coup avec lequel on a effectué l'edgeswapping, permettant ainsi d'exécuter n'importe quelle action dans l'immédiat juste après celui-ci.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Effectuer un des coups suivant (Bup de Zelda, Bcôté de Falco/Wolf, Bup de Marth, Bcôté de Metaknight, Bup de Pikachu, Bup de Samus ) de sorte à ce que le coup se heurte ou se termine sur un point précis de l'edge ou sur une bordure de plateforme, que vous soyez en dehors ou sur le terrain. Chaque coup cité ci-dessus a une façon particulière de créer l'edgewarpping.</p>
          <hr />
          <p style="text-align: justify;"><strong>Shield-Canceled Sliding Grab</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Comme vu ci-dessus dans la définition de <em>Grabs &amp; Throws</em>, il existe différents types de grabs qui ont des caractéristiques qui leurs sont propres (range, cooldown, etc. et qui sont différentes). Or certains personnages ont un meilleur grab sur place que leur dash grab. Cette technique vous permet donc d'exécuter un grab sur place tout en profitant d'une impulsion donnée par la glissade du shield.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Courir puis appuyer sur le bouclier (R/L) et sur A pendant le bouclier.</p>
          <hr />
          <p style="text-align: justify;"><strong>Edge Grabbing</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à grab un ennemi alors qu'il est accroché au bord. À noter que pour cela qui faut que ses frames d'invincibilité soient passées.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Lorsque votre adversaire est accroché au bord et que ses frames d'invincibilité sont passées, faites un dashing grab ou running grab le plus près possible du bord.</p>
          <hr />
          <p style="text-align: justify;"><strong>Missile-canceling</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à annuler le cooldown de certains projectiles lorsque vous ré-atterrissez au sol (Bcôté de Samus, Bneutre de Falco, Bneutre de Link/Toon Link, etc). C'est le même principe que les <em>Autocanceling Aerials</em>.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser&nbsp;</em>: Lancer un projectile pouvant être Missile-canceled lorsque l'on est en l'air au moment où l'on retouche le sol.</p>
          <hr />
          <p style="text-align: justify;"><strong>Dash Attack Shield Cancel</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à annuler votre dash attack sur l'edge, ou un bord de plateforme, en exécutant celle-ci sur le shield de votre adversaire pour exécuter par la suite l'aerial de votre choix. Le timing et la distance entre votre ennemi et l'edge requis pour cette technique dépendent de votre personnage. Ne fonctionne pas en cas de perfect shield de votre adversaire.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser</em>&nbsp;: Exécuter une Dash Attack sur le shield de votre adversaire au moment où celui-ci est proche (ou collé) du bord, vous tomberez ainsi dans le vide avec votre adversaire et vous pourrez effectuer l'aerial de votre choix.</p>
          <hr />
          <p style="text-align: justify;"><strong>Shield Break Ledge Cancel</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Consiste à annuler l'état de vulnérabilité du Shield Breaking en utilisant l'inclinaison d'un edge ou d'une bordure de plateforme (si l'inclinaison va en direction du vide). La seule exception étant pour Pikachu qui annule son état de vulnérabilité du shield breaking seulement grâce à l'edge sans prendre en compte l'inclinaison de celui-ci.</p>
          <hr />
          <p style="text-align: justify;"><strong>Jump Cancel Up Smash</strong><strong>&nbsp;:</strong>&nbsp;Consiste à annuler votre saut pendant un running pour effectuer un Usmash, le but étant de faire une glissade avant le Usmash, différente de celle du DACUS ou du Hyphen Smash. Cette technique trouve sa principale utilité lorsqu’elle est <em>renversée</em>.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser</em>&nbsp;: Running puis X ou Y + (Direction haute avec le stick directionnel + A pendant les premières frames du Jump (Maintenir A pour charger le Usmash)).</p>
          <hr />
          <p style="text-align: justify;"><strong>Reverse Jump Cancel Up Smash</strong><strong>&nbsp;</strong><strong>:</strong>&nbsp;Même principe que le Jump Cancel Up Smash, le but étant cette fois-ci d'effectuer une glissade tout en faisant un Usmash dans la direction opposée à la glissade. Cette technique peut donc être principalement utile pour les personnages qui ont un Usmash qui ne touche que d'un côté ou qui s'effectue en arc de cercle.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser</em>&nbsp;: Running + RAR + (Direction haute avec le stick directionnel + A pendant les premières frames du RAR (Maintenir A pour charger le Usmash)).</p>
          <hr />
          <p style="text-align: justify;"><strong>Forward Smash with an Item</strong><strong>&nbsp;:</strong>&nbsp;Consiste à faire un Fsmash avec un objet dans les mains sans relâcher celui-ci, le but étant de surprendre votre adversaire en le feintant avec un lancer de l'objet.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser</em>&nbsp;: Avoir un objet en main puis maintenir le bouton avec lequel vous avez attrapé l'objet, puis C-stick vers l'avant ou l'arrière (Le Fsmash se charge). Relâcher ensuite le bouton avec lequel vous avez attrapé l'objet pour exécuter votre Fsmash.</p>
          <hr />
          <p style="text-align: justify;"><strong>Jump Cancel Item-Throw</strong><strong>&nbsp;:</strong>&nbsp;Effet similaire au Glide Tossing ou à l'Item Boosting, le but étant cette fois-ci d'annuler un saut pour lancer un objet, ce qui aura pour effet de vous faire faire une glissade au moment où vous jetez celui-ci (Des glissades de longueurs différentes que celles faites avec le <em>Glide Tossing</em> ou l'<em>Item Boosting</em>). La longueur de votre glissade dépend du personnage avec lequel vous effectuez cette technique.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser</em>&nbsp;: Running (Facultatif) puis X ou Y + (Direction cardinale avec le stick directionnel + A pendant les premières frames du Jump).</p>
          <hr />
          <p style="text-align: justify;"><strong>Short Hop Air-Dodging (SHAD'ing)</strong><strong>&nbsp;:</strong>&nbsp;Consiste à exécuter un air-dodge avant de toucher le sol pour enchaîner n'importe lequel de vos coups immédiatement en profitant du système du buffer. Vous pouvez ainsi abuser de cette technique pour profiter de quelques frames d'invincibilité au sol puis enchaîner un coup rapide et qui se buff facilement afin de surprendre votre adversaire. Selon votre personnage il se peut que celui-ci fasse une petite glissade avant d'exécuter le coup que vous avez buff. On lui donne ce nom car cette technique est le plus souvent utilisée en short hop.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser</em>&nbsp;: Exécuter un air-dodge avant de toucher le sol de telle sorte que vous touchiez le sol avant que l'animation de votre air-dodge ne prenne fin, puis exécuter le coup de votre choix pendant votre air-dodge.</p>
          <hr />
          <p style="text-align: justify;"><strong>Turn around B &amp; B reversal</strong><strong>&nbsp;:</strong>&nbsp;Consiste à exécuter votre Neutral B dans la direction opposée à votre personnage. Il existe 2 méthodes pour exécuter cela, le Turn Around B et le B reversal, les 2 ayant des propriétés propres. En effet si vous sautez et exécutez un Turn Around B vous ferez un Neutral B dans la direction opposée tout en poursuivant votre élan dans la direction où vous avez sauté.</p>
          <p style="text-align: justify;">Si vous sautez et exécutez un B reversal, vous ferez un Neutral B dans la direction opposée mais vous stopperez votre élan (on appelle cela le Momentum) et vous continuerez celui-ci dans la direction opposée à celle où vous avez sauté. L'impulsion donnée par votre momentum dépendant du personnage avec lequel vous l'avez effectué.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser (Turn Around B)</em>&nbsp;: Relâcher le stick directionnel alors que celui-ci était positionné dans la direction opposée au personnage et appuyer sur B.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser (Turn Around B)</em>&nbsp;: Appuyer sur B + Incliner le stick directionnel dans la direction opposée à votre personnage pendant les premières frames du B.</p>
          <hr />
          <p style="text-align: justify;"><strong>Zero Acceleration Dash (ZAD)</strong><strong>&nbsp;:</strong>&nbsp;Consiste à faire un <em>Dashing</em> sans aucune accélération (ou presque), ceci vous faisant courir tout en restant sur place. Principalement utile pour feinter votre adversaire si vous possédez de bons Spéciaux ou un bon Fsmash en <em>Stuer/Back Stepping</em>.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Walking à pleine vitesse + Dashing dans la direction opposée au Walking (Ramener immédiatement le stick directionnel à sa position initiale après le Dashing).</p>
          <hr />
          <p style="text-align: justify;"><strong>Ledge Running</strong><strong>&nbsp;:</strong>&nbsp;Consiste à courir sur le bord sans tomber de celui-ci, autrement dit, vous courez sur place tout en restant sur le bord du terrain.</p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Utiliser la 3ème vitesse du X-Slow Run et se diriger vers le bord tout en maintenant cette vitesse.</p>
          <hr />
          <p style="text-align: justify;"><strong style="text-align: justify;">True Pivot</strong><strong style="text-align: justify;">&nbsp;:</strong><span style="text-align: justify;">&nbsp;</span><span style="text-align: justify;">Consiste à stopper votre personnage juste après un dash, le faire se retourner et le faire attaquer, tout cela à très grande vitesse.</span><span style="text-align: justify;">&nbsp;</span></p>
          <p style="text-align: justify;">•&nbsp;<em>Comment utiliser :</em>&nbsp;Dash-Dashing + Direction inverse avec le stick directionnel pendant les premières frames d'un dash pendant le Dash-Dashing + ( (A + direction) ou C-stick).</p>
          <hr />
          <p>Merci au site Eclypsia pour ce lexique complet.</p>

    </main>
    <footer>
      <?php include "assets/php/footer.php" ?>
    </footer>
    <?php include "assets/php/scripts.php" ?>
  </body>
</html>
